### PR TITLE
New PR Template Proposal

### PR DESCRIPTION
**Pull request by tnortman**
## Proposed Changes 🪄 

Creates a new Pull Request Template to adhere to for the MobileBytes org

## Issue ticket number and link

N/A

## Type of change

Please delete options that are not relevant.

-   [ ] 🐛  Bug fix (non-breaking change which fixes an issue)
-   [x] 🪄  New feature (non-breaking change which adds functionality)
-   [ ] 💥  Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] 📝 This change requires a documentation update

## Checklist before requesting a review:

-   [x] :scroll: My code follows the style guidelines of this project
-   [x] :monocle_face: I have performed a self-review of my code
-   [x] :memo: I have made corresponding changes to the documentation
-   [x] :test_tube: I have added tests that prove my fix is effective or that my feature works
-   [x] :white_check_mark: New and existing unit tests pass locally with my changes
-   [x] :warning: My changes generate no new warnings
-   [x] :speech_balloon: I have commented my code, particularly in hard-to-understand areas, or updated comments that may have been affected by my changes

### CODE REVIEW

**Comment by tnortman** [comment]
Migrate to `.github` for org wide PR template (continued from https://github.com/MobileBytes/serverless/pull/2964)

**Review by darrenjaworski — APPROVED** [review]
love!

**Comment by killrazor** [comment]
Love it as well

**Review by willMelo92 — APPROVED** [review]

**Comment by dvanno** [comment]
beauty <3

**Comment by killrazor** [comment]
What do you all think about this format? I know we could use something like this.

**Review by killrazor — APPROVED** [review]

**Pull request merged**
